### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by heinrichloewen** [sitcomlab/Ethics-app#21]
Hi,

I spotted some minor issues by going through the Ethics App:
- [x] The link in the email does not log me in, but brings me to the page where I have to specify the document-id.
- [x] On the Download there is a british flag in front of the german Informed consent form.
- [X] ~~I can go to the next page in the study description, although there are required field empty.~~
- [x] In the german consent form there is a double dot befor the name of the forscher.

**Comment by nicho90** [comment]
Hey @heinrichloewen, thank you for reporting the issues. I just fixed the 2nd and the 4th issue. The 3rd is the standard behaviour, so you can come back to the page, if you are not sure at the moment, what to write into the required fields, for example if you would input all English fields first and then decide to support German as well. But if you would hit the submit button, it will be checked, if all required fields has been filled out and missing fields will be highlighted red.
The 1st issue seems to be a problem on our production server. @SpeckiJ will take care of that soon.

**Comment by SpeckiJ** [comment]
I have fixed the configuration error in production and the Links should now work. I am sorry for any Inconvenience caused.

As all Points have been adressed I will close the Issue now.
