### ISSUE TITLE
Consent form for underage persons

### ISSUE THREAD

**Issue by nicho90** [sitcomlab/Ethics-app#22]
A consent form for underage persons, which need to be signed by their parents.

**Comment by SpeckiJ** [comment]
Progress can be tracked in the appropiate branch: https://github.com/sitcomlab/Ethics-app/tree/feature/third_party_consent

**Comment by nicho90** [comment]
Any updates on this issue?

**Comment by SpeckiJ** [comment]
This will not be implemented. Additional Consent Forms are handled via Question 14.
