### ISSUE TITLE
Additional custom "Questions"

### ISSUE THREAD

**Issue by SpeckiJ** [sitcomlab/Ethics-app#39]
To be able to process special Studies which can not be fitted to the roster of the predefined Questions it should be possible to attach additional Resources to the Study.

The Resources would be stored on the Server and handled the same way as regular questions with regards to comments by reviewers etc.

If there are multiple Files to be added for ethical evaluation they should be zipped so a single new "Question" should suffice.

**Comment by nicho90** [comment]
Sounds like a bigger feature. I suggest a new table for that in the database schema, otherwise it could be difficult to integrate that.

**Comment by SpeckiJ** [comment]
Implemented in #48
