### ISSUE TITLE
Password Generation

### ISSUE THREAD

**Issue by SpeckiJ** [sitcomlab/Ethics-app#43]
Due to security concerns it might not be ideal to store the passwords online. 

Password should be printed on the cover letter recieved when downloading the documents.

This creates the problem that on re-generation of the cover letter the password might not be the same. 

Handling is still TBD.

**Comment by nicho90** [comment]
Why not sending it by Email? For example, when an user specifically asks for it, by clicking on a button in the client? It could be implemented in the way, that the system always generates new password, which expires after 1 or 2 days. In this case, researchers can share it and work together on the same datastore.

**Comment by SpeckiJ** [comment]
Password Generation is implemented in #43

TODO: Update Howto Guide to reflect changes in Password acquisition.
